version: '3.8'

services:
  frontend:
    image: jinwanseo/mygpt_front:latest
    ports:
      - "80:3000"
    networks:
      - app_network

  backend:
    image: jinwanseo/mygpt_back:latest
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
